### ISSUE TITLE
Config not resolved

### ISSUE THREAD

**Issue by sandeshbagade** [somnonetz/copla-editor#11]
Hello sir ,
I tried clonning and running the application on my machine but you have not added the config file. Please let me know how can I set up config

**Comment by jmz-b** [comment]
@sandeshbagade Not the original author but I an working on this at the moment, I didn't get a notification for this so sorry for the late response.

To answer your question, to add a valid config file, create the file `sn-editor/src/config.js` and add something like the following:

```
const autologin = false;

const host = 'http://localhost/xnat/REST;

const credentials = {};

const doReconstruction = false;
const pipelineName = null;
const pipelineParams = {};

export { autologin, host, credentials, pipelineName, pipelineParams, doReconstruction }
```
